package edu.bu.met.cs665;

import edu.bu.met.cs665.entity.Customer;
import edu.bu.met.cs665.util.CustomerFactory;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 * This class contains unit tests for different types of customers generated by the CustomerFactory.
 */
public class CustomerTest {

    /**
     * Check if the email generated for a business customer is correct.
     */
    @Test
    public void testBusinessCustomerEmail() {
        Customer customer = CustomerFactory.createCustomer("business", "Alen");
        assertEquals("Dear Alen, thank you for being a valued business partner.", customer.generateEmail());
    }

    /**
     * Check if the email generated for a returning customer is correct.
     */
    @Test
    public void testReturningCustomerEmail() {
        Customer customer = CustomerFactory.createCustomer("returning", "Bob");
        assertEquals("Welcome back, Bob! We appreciate your continued loyalty.", customer.generateEmail());
    }

    /**
     * Check if the email generated for a frequent customer is correct.
     */
    @Test
    public void testFrequentCustomerEmail() {
        Customer customer = CustomerFactory.createCustomer("frequent", "Charles");
        assertEquals("Hello Charles, thanks for being one of our frequent customers!", customer.generateEmail());
    }

    /**
     * Check if the email generated for a new customer is correct.
     */
    @Test
    public void testNewCustomerEmail() {
        Customer customer = CustomerFactory.createCustomer("new", "David");
        assertEquals("Welcome David! Thank you for joining our community.", customer.generateEmail());
    }

    /**
     * Check if the email generated for a VIP customer is correct.
     */
    @Test
    public void testVIPCustomerEmail() {
        Customer customer = CustomerFactory.createCustomer("vip", "Eva");
        assertEquals("Dear VIP Eva, we are honored to serve you with exclusive offers.", customer.generateEmail());
    }
}
