package edu.bu.met.cs665.entity;

/**
 * This class represents a delivery request generated by a shop.
 * It contains information about the order such as the order ID and the delivery address.
 */
public class DeliveryRequest {

    // The unique identifier for the order
    private final String orderId;

    // The delivery address for the order
    private final String address;

    /**
     * Constructor to initialize the delivery request with an order ID and delivery address.
     *
     * @param orderId  The unique ID of the order
     * @param address  The address where the order should be delivered
     */
    public DeliveryRequest(String orderId, String address) {
        this.orderId = orderId;
        this.address = address;
    }

    /**
     * Returns the details of the delivery request as a formatted string.
     *
     * @return A string containing the order ID and the delivery address
     */
    public String getDetails() {
        return "Order ID: " + orderId + ", Address: " + address;
    }
}
